version: '3'

services:
  sentry-log:
    image: sentrylog:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./resources/custom.md:/usr/src/app/templates/custom.md
    restart: always
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ANTHROPIC_MODEL_ID=${ANTHROPIC_MODEL_ID}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL}
      - TEMPLATE=${TEMPLATE:-custom.md}
      - CONTAINER_TO_WATCH=nginx