name: Docker

on:
  push:
    tags:
      - '*'

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      run: |
        docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

    - name: Run tests
      run: |
        docker-compose -f docker-compose.yml up -d sentry-log
        docker-compose -f docker-compose.yml exec -T sentry-log /usr/local/bin/pytest -vv /usr/src/app/

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 -t grgrlmml/sentrylog:${GITHUB_REF#refs/tags/} -t grgrlmml/sentrylog:latest --push .
